app = 'js-status'
primary_region = 'syd'

[[mounts]]
  source = 'kuma_data'
  destination = '/app/data'

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '512mb'
  cpu_kind = 'shared'
  cpus = 1

[env]
  TZ = "Pacific/Auckland"

